-- Phase 0: Create Backup Tables for Development
-- Date: 2026-04-17
-- Purpose: Create backup copies of production tables for safe development/testing

-- Create backup of BUSINESS_UNIT_DETAILS
CREATE TABLE ODS.PUBLIC.ZZZ_BUSINESS_UNIT_DETAILS_20260417 AS
SELECT * FROM ODS.PUBLIC.BUSINESS_UNIT_DETAILS;

-- Create backup of BUSINESS_UNIT_WEB_NAME
CREATE TABLE ODS.PUBLIC.ZZZ_BUSINESS_UNIT_WEB_NAME_20260417 AS
SELECT * FROM ODS.PUBLIC.BUSINESS_UNIT_WEB_NAME;

-- Verify row counts match
SELECT
    'BUSINESS_UNIT_DETAILS (PROD)' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT
FROM ODS.PUBLIC.BUSINESS_UNIT_DETAILS
UNION ALL
SELECT
    'ZZZ_BUSINESS_UNIT_DETAILS_20260417 (BACKUP)',
    COUNT(*)
FROM ODS.PUBLIC.ZZZ_BUSINESS_UNIT_DETAILS_20260417
UNION ALL
SELECT
    'BUSINESS_UNIT_WEB_NAME (PROD)',
    COUNT(*)
FROM ODS.PUBLIC.BUSINESS_UNIT_WEB_NAME
UNION ALL
SELECT
    'ZZZ_BUSINESS_UNIT_WEB_NAME_20260417 (BACKUP)',
    COUNT(*)
FROM ODS.PUBLIC.ZZZ_BUSINESS_UNIT_WEB_NAME_20260417;
